server:
  port: 9999

jwt:
  secret: xxxxx.xxxx.xxxx
  expire: 86400
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hong.library.domain
